from django.db import models

class States(models.TextChoices):
    AGUASCALIENTES = "AGU", "Aguascalientes"
    BAJA_CALIFORNIA = "BCN", "Baja California"
    BAJA_CALIFORNIA_SUR = "BCS", "Baja California Sur"
    CAMPECHE = "CAM", "Campeche"
    CHIAPAS = "CHP", "Chiapas"
    CHIHUAHUA = "CHH", "Chihuahua"
    CIUDAD_DE_MEXICO = "CDMX", "Ciudad de México"
    COAHUILA = "COA", "Coahuila"
    COLIMA = "COL", "Colima"
    DURANGO = "DUR", "Durango"
    GUANAJUATO = "GUA", "Guanajuato"
    GUERRERO = "GRO", "Guerrero"
    HIDALGO = "HID", "Hidalgo"
    JALISCO = "JAL", "Jalisco"
    ESTADO_DE_MEXICO = "MEX", "Estado de México"
    MICHOACAN = "MIC", "Michoacán"
    MORELOS = "MOR", "Morelos"
    NAYARIT = "NAY", "Nayarit"
    NUEVO_LEON = "NLE", "Nuevo León"
    OAXACA = "OAX", "Oaxaca"
    PUEBLA = "PUE", "Puebla"
    QUERETARO = "QUE", "Querétaro"
    QUINTANA_ROO = "ROO", "Quintana Roo"
    SAN_LUIS_POTOSI = "SLP", "San Luis Potosí"
    SINALOA = "SIN", "Sinaloa"
    SONORA = "SON", "Sonora"
    TABASCO = "TAB", "Tabasco"
    TAMAULIPAS = "TAM", "Tamaulipas"
    TLAXCALA = "TLA", "Tlaxcala"
    VERACRUZ = "VER", "Veracruz"
    YUCATAN = "YUC", "Yucatán"
    ZACATECAS = "ZAC", "Zacatecas"