# Generated by Django 4.0.5 on 2022-06-21 00:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('Text_EComments', models.TextField(default='')),
                ('Texto_de_agradecimiento', wagtail.core.fields.RichTextField(blank=True)),
                ('Image_EComments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_de_comentarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ConocenosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Texto_del_cuadro', models.CharField(default='', max_length=150)),
                ('Título_del_mapa', models.CharField(default='', max_length=60)),
                ('Título_principal', models.CharField(default='', max_length=40)),
                ('Texto_principal', wagtail.core.fields.RichTextField()),
                ('Primer_título', models.CharField(default='', max_length=40)),
                ('Texto_1er_título', wagtail.core.fields.RichTextField()),
                ('Segundo_título', models.CharField(default='', max_length=40)),
                ('Texto_2ndo_título', wagtail.core.fields.RichTextField()),
                ('Tercer_título', models.CharField(default='', max_length=40)),
                ('Texto_3er_título', wagtail.core.fields.RichTextField()),
                ('Separador_colab', models.CharField(default='', max_length=50)),
                ('Texto1', wagtail.core.fields.RichTextField()),
                ('Texto2', wagtail.core.fields.RichTextField(default='')),
                ('Imagen_1er_título', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_2ndo_título', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_3er_título', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_en_el_cuadro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Texto_de_bienvenida', models.CharField(default='', max_length=200)),
                ('Separador_servicios', models.CharField(default='', max_length=50)),
                ('Separador_anuncios', models.CharField(default='', max_length=50)),
                ('Titulo_izq', models.CharField(default='', max_length=40)),
                ('Texto_izq', models.CharField(default='', max_length=120)),
                ('Titulo_der', models.CharField(default='', max_length=40)),
                ('Texto_der', models.CharField(default='', max_length=120)),
                ('Imagen_categoría_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_categoría_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_categoría_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_categoría_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_de_bienvenida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_der', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_izq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PreguntasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Título_principal', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiciosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Descripción_servicio', wagtail.core.fields.RichTextField(default='')),
                ('category', models.TextField(choices=[('HOGAR', 'HOGAR'), ('ELECTRICIDAD', 'ELECTRICIDAD'), ('PINTURA', 'PINTURA'), ('CONSTRUCCIÓN', 'CONSTRUCCIÓN')], default='HOGAR', max_length=12)),
                ('Título_de_ventana', models.CharField(default='COTIZACIONES', max_length=25)),
                ('Descripción_1', wagtail.core.fields.RichTextField(default='Es posible que el precio cambie dependiendo del tipo de trabajo que se requiera, estos son solo precios de referencia')),
                ('Título_columna_1', models.CharField(default='Actividad', max_length=15)),
                ('Texto_1_columna_1', models.CharField(default='Visita', max_length=35)),
                ('Texto_2_columna_1', models.CharField(default='Servicios de mano de obra', max_length=35)),
                ('Título_columna_2', models.CharField(default='Precio', max_length=15)),
                ('Texto_1_columna_2', models.CharField(default='$200', max_length=35)),
                ('Texto_2_columna_2', models.CharField(default='$400', max_length=12)),
                ('Descripción_2', wagtail.core.fields.RichTextField(default='*Si aceptan la cotización/el servicio, se descuenta el precio de visita')),
                ('Imagen_principal_del_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiciosImages',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_images', to='home.serviciospage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantPregunta',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(default='', max_length=100)),
                ('respuesta', models.CharField(default='', max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_preguntas', to='home.preguntaspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plantilla_servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Título_trabajos_hechos', models.CharField(default='', max_length=40)),
                ('Título_sección_cotizar', models.CharField(default='', max_length=40)),
                ('Título_cuadro_1', models.CharField(default='', max_length=24)),
                ('Descripción_cuadro_1', wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(280)])),
                ('Título_cuadro_2', models.CharField(default='', max_length=24)),
                ('Descripción_cuadro_2', wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(130)])),
                ('Boton_cuadro_2', models.CharField(default='', max_length=15)),
                ('Título_cuadro_3', models.CharField(default='', max_length=24)),
                ('Descripción_cuadro_3', wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(130)])),
                ('Boton_cuadro_3', models.CharField(default='', max_length=15)),
                ('Icono_cuadro_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Icono_cuadro_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Icono_cuadro_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageCarouselImages',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo_slide', models.CharField(max_length=50)),
                ('Texto_slide', models.CharField(max_length=150)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Navegación_1', models.CharField(default='Inicio', max_length=8)),
                ('Navegación_2', models.CharField(default='Servicios', max_length=11)),
                ('Navegación_3', models.CharField(default='Conócenos', max_length=11)),
                ('Navegación_4', models.CharField(default='Contáctanos', max_length=11)),
                ('Logo_barra_de_navegación', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.commentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_de_la_empresa', models.CharField(default='Grupo LIAS', max_length=15)),
                ('Dirección_de_la_empresa', models.CharField(default='C. Pisperama 180-interior. 6, Vista Bella, 58090 Morelia, Mich.', max_length=100)),
                ('Título_sección_izquierda', models.CharField(default='OTROS ENLACES', max_length=20)),
                ('Enlace_1', models.CharField(default='Conócenos', max_length=20)),
                ('Enlace_2', models.CharField(default='Preguntas frecuentes', max_length=20)),
                ('Enlace_3', models.CharField(default='Comentarios', max_length=20)),
                ('Título_sección_derecha', models.CharField(default='CONTACTO', max_length=20)),
                ('Enlace_4', models.CharField(default='Contáctanos', max_length=20)),
                ('Celular', models.CharField(default='443-471-4356', max_length=16)),
                ('Link_a_celular', models.CharField(default='4434714356', max_length=13)),
                ('Teléfono', models.CharField(default='554-833-5729', max_length=16)),
                ('Link_a_teléfono', models.CharField(default='+525548335729', max_length=13)),
                ('Enlace_5', models.CharField(default='grupolias@hotmail.com', max_length=40)),
                ('Título_sección_de_redes', models.CharField(default='SIGUENOS EN NUESTRAS REDES', max_length=40)),
                ('Link_a_red_social1', models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200)),
                ('Link_a_red_social2', models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200)),
                ('Logo_red_social1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_red_social2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Usuario_Red_Social_1', models.CharField(default='', max_length=20)),
                ('Link_a_Red_Social_1', models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200)),
                ('Usuario_Red_Social_2', models.CharField(default='', max_length=20)),
                ('Link_a_Red_Social_2', models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200)),
                ('Telefono_1', models.CharField(default='', max_length=16)),
                ('Link_a_Telefono_1', models.CharField(default='4434714356', max_length=13)),
                ('Telefono_2', models.CharField(default='', max_length=16)),
                ('Link_a_Telefono_2', models.CharField(default='+525548335729', max_length=13)),
                ('Correo_electronico', models.CharField(default='', max_length=35)),
                ('Url_Maps', models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3756.8164504686365!2d-101.19980278513917!3d19.677834686745502!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842d0d305391c24b%3A0x40f2a314c0cf0326!2sGRUPO%20LIAS!5e0!3m2!1ses!2smx!4v1650404689145!5m2!1ses!2smx', help_text="Esta URL se consigue en google maps en la etiqueta compartir y en la pestaña 'Incorporar un mapa', se copia todo el link que está en el apartado 'src=' sin las comillas", max_length=500)),
                ('Correo_electronico_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_Red_Social_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_Red_Social_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_Telefono_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_Telefono_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ConocenosPageSlider',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='home.conocenospage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
