# Generated by Django 6.0.3 on 2026-05-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_servicerequest_alter_footer_link_a_celular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
