# Generated by Django 6.0.3 on 2026-05-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('vidrio y aluminio', 'Vidrio y aluminio'), ('herreria', 'Herrería'), ('levantamiento de informacion', 'Levantamiento de información'), ('carpinteria', 'Carpintería'), ('impermeabilizacion', 'Impermeabilización'), ('pintura', 'Pintura'), ('remodelacion', 'Remodelación'), ('ampliacion', 'Ampliación'), ('aire acondicionado', 'Aire acondicionado'), ('cerrajería', 'Cerrajería'), ('diseño', 'Diseño'), ('proyecto', 'Proyecto')], max_length=50)),
                ('service_description', models.TextField()),
                ('technician_name', models.CharField(max_length=255)),
                ('operator_responsible', models.CharField(max_length=255)),
                ('assigned_by', models.CharField(max_length=255)),
                ('request_date', models.DateField()),
                ('request_time', models.TimeField()),
                ('execution_date', models.DateField(null=True)),
                ('completion_date', models.DateField(null=True)),
                ('payment_date', models.DateField(null=True)),
                ('place_name', models.CharField(max_length=255)),
                ('place_manager_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('state', models.CharField(choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHH', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DUR', 'Durango'), ('GUA', 'Guanajuato'), ('GRO', 'Guerrero'), ('HID', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QUE', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLA', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=5)),
                ('work_description', models.TextField()),
                ('technician_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('partial', 'Parcial'), ('late', 'Retrasado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('general_observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
