# Generated by Django 6.0.3 on 2026-05-08 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_time',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de solicitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='assigned_by',
            field=models.CharField(max_length=255, verbose_name='Asignado por'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='company_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Grupo LIAS'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='completion_date',
            field=models.DateField(null=True, verbose_name='Fecha de termino'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='execution_date',
            field=models.DateField(null=True, verbose_name='Fecha de realización'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='general_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='operator_responsible',
            field=models.CharField(max_length=255, verbose_name='Responsable del seguimiento'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_date',
            field=models.DateField(null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('partial', 'Parcial'), ('late', 'Retrasado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='place_manager_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del encargado del lugar'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='place_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del lugar'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_description',
            field=models.TextField(verbose_name='Tema a realizar o resolver'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('vidrio y aluminio', 'Vidrio y aluminio'), ('herreria', 'Herrería'), ('levantamiento de informacion', 'Levantamiento de información'), ('carpinteria', 'Carpintería'), ('impermeabilizacion', 'Impermeabilización'), ('pintura', 'Pintura'), ('remodelacion', 'Remodelación'), ('ampliacion', 'Ampliación'), ('aire acondicionado', 'Aire acondicionado'), ('cerrajería', 'Cerrajería'), ('diseño', 'Diseño'), ('proyecto', 'Proyecto')], max_length=50, verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='state',
            field=models.CharField(choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHH', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DUR', 'Durango'), ('GUA', 'Guanajuato'), ('GRO', 'Guerrero'), ('HID', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QUE', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLA', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=5, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='technician_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del técnico'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='technician_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del técnico'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='work_description',
            field=models.TextField(verbose_name='Descripción de lo que se realizó'),
        ),
    ]
