# Generated by Django 6.0.3 on 2026-05-08 23:10

import django.db.models.deletion
import modelcluster.fields
import service_tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_tracking', '0002_remove_servicerequest_request_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=service_tracking.models.service_request_image_upload_to)),
                ('service_request', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_result_images', to='service_tracking.servicerequest')),
            ],
        ),
    ]
