# Generated by Django 6.0.3 on 2026-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_tracking', '0003_servicerequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('in_progress', 'En proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado del servicio'),
        ),
    ]
