# Generated by Django 6.0.3 on 2026-05-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_tracking', '0004_servicerequest_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de termino'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de realización'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='general_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='technician_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo del técnico'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='work_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de lo que se realizó'),
        ),
    ]
