# Generated by Django 6.0.3 on 2026-05-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_tracking', '0005_alter_servicerequest_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'permissions': [('view_dashboard', 'Can view dashboard')]},
        ),
    ]
